<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::create([
            'name' => 'Logitech Mouse',
            'price' => 150000.00,
            'stock' => 10,
            'description' => 'High-spec gaming mouse, suitable for gaming and multimedia needs.',
            'image' => '/assets/images/products/logitech-mouse.png', 
            'sold' => 100,
            'detail' => 'Ergonomic design, high-precision sensor, customizable buttons, and durable build. Suitable for gamers and professionals.',
            'specification' => 'DPI: 16000, Sensor: Optical, Buttons: 6 programmable, Connectivity: Wired USB, Weight: 90 grams',
            'important_information' => 'Compatible with Windows and macOS. Requires USB 2.0 or higher. Warranty: 2 years.',
            'original_price' => 200000.00,
            'discount' => 25,
            'sale' => true,
            'category_id' => 5, 
            'brand_id' => 11, 
        ]);

        Product::create([
            'name' => 'Logitech Keyboard',
            'price' => 250000.00,
            'stock' => 15,
            'description' => 'High-spec gaming keyboard, suitable for gaming and multimedia needs.',
            'image' => '/assets/images/products/keyboard.png',
            'sold' => 50,
            'detail' => 'Mechanical keys with RGB lighting, durable build for long-lasting use.',
            'specification' => 'Connectivity: Wired, Switch Type: Mechanical, Backlight: RGB, Weight: 1.2kg',
            'important_information' => 'Compatible with Windows and macOS, 2-year manufacturer warranty.',
            'original_price' => 285000.00, 
            'discount' => 12, 
            'sale' => false,
            'category_id' => 5, 
            'brand_id' => 11, 
        ]);
        
        Product::create([
            'name' => 'Lenovo Yoga 7',
            'price' => 17850000,
            'stock' => 15,
            'description' => '2-in-1 laptop, suitable for multimedia, work, and portability.',
            'image' => '/assets/images/products/laptop.png',
            'sold' => 40,
            'detail' => 'Convertible design with touchscreen, supports pen input.',
            'specification' => 'Processor: Intel Core i7, RAM: 16GB, Storage: 512GB SSD, Display: 14" FHD Touchscreen',
            'important_information' => 'Windows 11 pre-installed, 1-year manufacturer warranty.',
            'original_price' => 20500000.00, 
            'discount' => 15, 
            'sale' => true,
            'category_id' => 1,
            'brand_id' => 5, 
        ]);
        
        Product::create([
            'name' => 'Asus Studiobook',
            'price' => 17850000,
            'stock' => 15,
            'description' => 'High-performance laptop for creatives and professionals.',
            'image' => '/assets/images/products/proart.png',
            'sold' => 35,
            'detail' => 'Powerful performance for video editing and 3D rendering.',
            'specification' => 'Processor: Intel Core i9, RAM: 32GB, Storage: 1TB SSD, GPU: NVIDIA RTX 3060',
            'important_information' => 'Comes with ASUS ProArt Creator Hub for advanced performance tuning.',
            'original_price' => 21000000.00, 
            'discount' => 15, 
            'sale' => false,
            'category_id' => 1, 
            'brand_id' => 1, 
        ]);
        
        Product::create([
            'name' => 'Zenbook Duo',
            'price' => 32000000,
            'stock' => 10,
            'description' => 'Premium dual-screen laptop, ideal for multitasking and creatives.',
            'image' => '/assets/images/products/zenbook duo.png',
            'sold' => 10,
            'detail' => 'Secondary touchscreen display for enhanced productivity.',
            'specification' => 'Processor: Intel Core i7, RAM: 16GB, Storage: 1TB SSD, Display: 14" main + 12" secondary display',
            'important_information' => 'Supports stylus input, Windows 11 pre-installed.',
            'original_price' => 40000000.00, 
            'discount' => 20, 
            'sale' => true,
            'category_id' => 1, 
            'brand_id' => 1, 
        ]);
        Product::create([
            'name' => 'PIXMA E3470',
            'price' => 2000000,
            'stock' => 20,
            'description' => 'High-spec printer, suitable for office and multimedia needs.',
            'image' => '/assets/images/products/printer.png', 
            'sold' => 10,
            'detail' => 'Compact and versatile, perfect for home and office use.',
            'specification' => 'Print, copy, scan, and wireless capabilities.',
            'important_information' => 'Includes ink cartridges and setup CD.',
            'original_price' => 2500000.00, 
            'discount' => 20, 
            'sale' => false,
            'category_id' => 8, 
            'brand_id' => 20, 
        ]);
        
        Product::create([
            'name' => 'Sony WH-1000xm5',
            'price' => 6000000,
            'stock' => 12,
            'description' => 'High-spec headphones, suitable for listening and multimedia needs.',
            'image' => '/assets/images/products/headphone.png',
            'sold' => 10,
            'detail' => 'Noise-canceling technology with high-fidelity sound.',
            'specification' => 'Bluetooth, 30 hours battery life, touch controls.',
            'important_information' => 'Compatible with voice assistants.',
            'original_price' => 7000000.00,
            'discount' => 15, 
            'sale' => true,
            'category_id' => 5, 
            'brand_id' => 19, 
        ]);
        
        Product::create([
            'name' => 'Rexus Xierra X16',
            'price' => 165000,
            'stock' => 30,
            'description' => 'High-spec mouse, suitable for gaming and multimedia needs.',
            'image' => '/assets/images/products/MOUSE REXUS.png', 
            'sold' => 10,
            'detail' => 'Ergonomic design with customizable RGB lighting.',
            'specification' => 'DPI up to 3200, 6 programmable buttons.',
            'important_information' => 'Plug-and-play, no drivers needed.',
            'original_price' => 200000.00,
            'discount' => 10, 
            'sale' => false,
            'category_id' => 5, 
            'brand_id' => 12, 
        ]);
        
        Product::create([
            'name' => 'Tuf Gaming F15',
            'price' => 12100000,
            'stock' => 15,
            'description' => 'High-spec gaming laptop, suitable for gaming and multimedia needs.',
            'image' => '/assets/images/products/laptoptuf.png', 
            'sold' => 50,
            'detail' => 'Durable design with a powerful cooling system.',
            'specification' => 'Intel Core i7, GTX 1650, 16GB RAM, 1TB SSD.',
            'important_information' => 'Includes gaming software and warranty.',
            'original_price' => 14000000.00,
            'discount' => 15, 
            'sale' => true,
            'category_id' => 1, 
            'brand_id' => 1, 
        ]);
        
        Product::create([
            'name' => 'ASUS ROG Zephyrus G14',
            'price' => 25000000,
            'stock' => 7,
            'description' => 'High-performance gaming laptop with AMD Ryzen processor and RTX graphics.',
            'image' => '/assets/images/products/rog_zephyrus.png',
            'sold' => 20,
            'detail' => 'Ultra-slim design with powerful gaming capabilities.',
            'specification' => 'AMD Ryzen 9, RTX 3060, 32GB RAM, 1TB SSD.',
            'important_information' => 'RGB keyboard and customizable settings.',
            'original_price' => 28000000.00,
            'discount' => 10, 
            'sale' => false,
            'category_id' => 1, 
            'brand_id' => 1, 
        ]);
        
        Product::create([
            'name' => 'Dell XPS Desktop',
            'price' => 22000000,
            'stock' => 8,
            'description' => 'Powerful desktop for heavy multitasking and content creation.',
            'image' => '/assets/images/products/dell_xps.png',
            'sold' => 12,
            'detail' => 'High-performance components for professional work.',
            'specification' => 'Intel Core i9, 64GB RAM, 2TB SSD.',
            'important_information' => 'Supports dual monitor setup.',
            'original_price' => 25000000.00,
            'discount' => 12, 
            'sale' => true,
            'category_id' => 2, 
            'brand_id' => 4, 
        ]);
        
        Product::create([
            'name' => 'Corsair K95 RGB Platinum',
            'price' => 2800000,
            'stock' => 25,
            'description' => 'Mechanical gaming keyboard with customizable RGB lighting.',
            'image' => '/assets/images/products/corsair_k95.png',
            'sold' => 18,
            'detail' => 'Durable key switches and dedicated macro keys.',
            'specification' => 'RGB backlighting, USB pass-through, 100% anti-ghosting.',
            'important_information' => 'Compatible with Corsair iCUE software.',
            'original_price' => 3200000.00,
            'discount' => 15, 
            'sale' => false,
            'category_id' => 5, 
            'brand_id' => 10, 
        ]);
        
        Product::create([
            'name' => 'HP LaserJet Pro MFP M428fdw',
            'price' => 4000000,
            'stock' => 20,
            'description' => 'Fast and reliable multifunction printer, perfect for office use.',
            'image' => '/assets/images/products/hp_laserjet.png',
            'sold' => 25,
            'detail' => 'Print, copy, scan, and fax capabilities.',
            'specification' => 'Automatic document feeder, wireless printing.',
            'important_information' => 'Energy-efficient design.',
            'original_price' => 4500000.00,
            'discount' => 11, 
            'sale' => true,
            'category_id' => 8, 
            'brand_id' => 3, 
        ]);
        
        Product::create([
            'name' => 'Acer Predator Helios 300',
            'price' => 22000000,
            'stock' => 8,
            'description' => 'High-performance gaming laptop with Intel Core i7 and RTX 3060 GPU.',
            'image' => '/assets/images/products/acer_predator.png',
            'sold' => 20,
            'detail' => 'Designed for gamers with advanced cooling and performance.',
            'specification' => 'Intel Core i7, RTX 3060, 16GB RAM, 1TB SSD.',
            'important_information' => 'RGB keyboard and high-refresh-rate display.',
            'original_price' => 24000000.00,
            'discount' => 8, 
            'sale' => false,
            'category_id' => 1, 
            'brand_id' => 2, 
        ]);
        
        Product::create([
            'name' => 'Dell XPS 13',
            'price' => 18000000,
            'stock' => 6,
            'description' => 'Ultrabook with Intel Core i5 and InfinityEdge display, ideal for professionals.',
            'image' => '/assets/images/products/dell_xps_13.png',
            'sold' => 9,
            'detail' => 'Sleek design with an ultra-thin profile.',
            'specification' => 'Intel Core i5, 16GB RAM, 512GB SSD.',
            'important_information' => 'Long battery life and lightweight design.',
            'original_price' => 20000000.00,
            'discount' => 10, 
            'sale' => true,
            'category_id' => 1, 
            'brand_id' => 4, 
        ]);
        
        Product::create([
            'name' => 'Lenovo ThinkPad X1 Carbon',
            'price' => 23000000,
            'stock' => 7,
            'description' => 'Business-class ultrabook with Intel Core i7, built for productivity.',
            'image' => '/assets/images/products/lenovo_thinkpad.png',
            'sold' => 11,
            'detail' => 'Durable construction with business-class performance.',
            'specification' => 'Intel Core i7, 16GB RAM, 1TB SSD.',
            'important_information' => 'Includes security features for business users.',
            'original_price' => 25000000.00,
            'discount' => 8, 
            'sale' => false,
            'category_id' => 1, 
            'brand_id' => 5, 
        ]);
        
        Product::create([
            'name' => 'Apple MacBook Pro 14-inch',
            'price' => 35000000,
            'stock' => 4,
            'description' => 'High-performance MacBook Pro with M1 chip, perfect for creative professionals.',
            'image' => '/assets/images/products/macbook_pro.png',
            'sold' => 15,
            'detail' => 'Retina display and powerful processing capabilities.',
            'specification' => 'Apple M1, 16GB RAM, 512GB SSD.',
            'important_information' => 'Battery life up to 20 hours.',
            'original_price' => 38000000.00,
            'discount' => 8, 
            'sale' => true,
            'category_id' => 1, 
            'brand_id' => 6, 
        ]);

        Product::create([
            'name' => 'MSI Stealth 15M',
            'price' => 18000000,
            'stock' => 9,
            'description' => 'Portable gaming laptop with Intel Core i7 and RTX 3060, ideal for gamers on the go.',
            'image' => '/assets/images/products/msi_stealth.png',
            'sold' => 7,
            'detail' => 'Lightweight design with powerful graphics capabilities.',
            'specification' => 'Intel Core i7, RTX 3060, 16GB RAM, 1TB SSD.',
            'important_information' => 'RGB keyboard and high-refresh-rate display.',
            'original_price' => 20000000.00,
            'discount' => 10, 
            'sale' => false,
            'category_id' => 1, 
            'brand_id' => 6, 
        ]);

        Product::create([
            'name' => 'Apple MacBook Air M2',
            'price' => 23000000,
            'stock' => 12,
            'description' => 'Ultra-light laptop with the powerful Apple M2 chip and Retina display.',
            'image' => '/assets/images/products/macbook_air_m2.png',
            'sold' => 30,
            'detail' => 'Exceptional battery life and sleek design for portability.',
            'specification' => 'Apple M2 chip, 8GB RAM, 256GB SSD.',
            'important_information' => 'Fanless design for silent operation.',
            'original_price' => 25000000.00,
            'discount' => 8, 
            'sale' => true,
            'category_id' => 1, 
            'brand_id' => 7, 
        ]);

        Product::create([
            'name' => 'Samsung 980 Pro 1TB NVMe SSD',
            'price' => 3000000,
            'stock' => 12,
            'description' => 'High-speed PCIe Gen4 NVMe SSD with 7000MB/s read speed, ideal for gaming and productivity.',
            'image' => '/assets/images/products/samsung_ssd.png',
            'sold' => 7,
            'detail' => 'Fast storage solution for high-performance computing.',
            'specification' => '1TB capacity, PCIe 4.0 interface.',
            'important_information' => 'Compatible with most laptops and desktops.',
            'original_price' => 3500000.00,
            'discount' => 15, 
            'sale' => false,
            'category_id' => 6, 
            'brand_id' => 8, 
        ]);

        Product::create([
            'name' => 'TP-Link Archer AX6000',
            'price' => 4000000,
            'stock' => 10,
            'description' => 'Wi-Fi 6 router with 8 Gigabit LAN ports and 4804Mbps wireless speed.',
            'image' => '/assets/images/products/tp_link_router.png',
            'sold' => 6,
            'detail' => 'High-speed connectivity for multiple devices.',
            'specification' => 'Supports Wi-Fi 6, 8 LAN ports, MU-MIMO technology.',
            'important_information' => 'Easy setup via TP-Link Tether app.',
            'original_price' => 4500000.00,
            'discount' => 11, 
            'sale' => true,
            'category_id' => 7, 
            'brand_id' => 17, 
        ]);

        Product::create([
            'name' => 'Microsoft Office 365',
            'price' => 1500000,
            'stock' => 100,
            'description' => 'Subscription-based productivity software suite for home and office use.',
            'image' => '/assets/images/products/office_365.png',
            'sold' => 70,
            'detail' => 'Access to Word, Excel, PowerPoint, and more.',
            'specification' => 'Subscription service with cloud storage.',
            'important_information' => 'Includes regular updates and support.',
            'original_price' => 2000000.00,
            'discount' => 25, 
            'sale' => false,
            'category_id' => 9, 
            'brand_id' => 12, 
        ]);

        Product::create([
            'name' => 'LG UltraFine 5K',
            'price' => 12000000,
            'stock' => 10,
            'description' => '5K monitor designed for creative professionals.',
            'image' => '/assets/images/products/lg_ultrafine_5k.png',
            'sold' => 15,
            'detail' => 'High color accuracy with P3 wide color gamut, ideal for designers.',
            'specification' => '27", 5120x2880, Thunderbolt 3, P3 wide color gamut',
            'important_information' => 'Great for video editing and graphic design.',
            'original_price' => 13000000.00,
            'discount' => 8,
            'sale' => true,
            'category_id' => 3, 
            'brand_id' => 9, 
        ]);

        Product::create([
            'name' => 'Apple iMac 24"',
            'price' => 25000000,
            'stock' => 5,
            'description' => 'All-in-one desktop with M1 chip and Retina display.',
            'image' => '/assets/images/products/imac_24.png',
            'sold' => 12,
            'detail' => 'Sleek design, 4.5K Retina display, and excellent performance.',
            'specification' => 'M1 chip, 8GB RAM, 256GB SSD, 4.5K Retina Display',
            'important_information' => 'Comes with Magic Keyboard and Magic Mouse.',
            'original_price' => 27000000.00,
            'discount' => 7,
            'sale' => false,
            'category_id' => 2, 
            'brand_id' => 7,
        ]);

        Product::create([
            'name' => 'HP Pavilion Gaming Desktop',
            'price' => 15000000,
            'stock' => 8,
            'description' => 'High-performance gaming desktop with Ryzen 7 and GTX 1660.',
            'image' => '/assets/images/products/hp_pavilion_gaming.png',
            'sold' => 18,
            'detail' => 'Perfect for mid-range gaming and content creation.',
            'specification' => 'AMD Ryzen 7, GTX 1660, 16GB RAM, 512GB SSD',
            'important_information' => 'Includes gaming mouse and keyboard.',
            'original_price' => 17000000.00,
            'discount' => 10,
            'sale' => true,
            'category_id' => 2,
            'brand_id' => 3,
        ]);

        Product::create([
            'name' => 'Intel Core i9-12900K',
            'price' => 9000000,
            'stock' => 30,
            'description' => '12th Gen Intel Core processor, ideal for gaming and productivity.',
            'image' => '/assets/images/products/intel_i9.png',
            'sold' => 50,
            'detail' => '16 cores, 24 threads, and turbo boost up to 5.2GHz.',
            'specification' => '16 cores, 24 threads, 5.2GHz boost clock, LGA 1700 socket',
            'important_information' => 'Compatible with Intel 600-series motherboards.',
            'original_price' => 10000000.00,
            'discount' => 10,
            'sale' => false,
            'category_id' => 4, 
            'brand_id' => 13,
        ]);

        Product::create([
            'name' => 'ASUS ROG Swift PG259QN',
            'price' => 9500000,
            'stock' => 15,
            'description' => '24.5" esports monitor with 360Hz refresh rate.',
            'image' => '/assets/images/products/asus_pg259qn.png',
            'sold' => 40,
            'detail' => 'Ultra-fast 360Hz refresh rate, 1ms response time, NVIDIA G-Sync.',
            'specification' => '24.5", 360Hz, 1920x1080, 1ms, G-Sync',
            'important_information' => 'Designed for competitive gaming.',
            'original_price' => 10000000.00,
            'discount' => 5,
            'sale' => true,
            'category_id' => 3, 
            'brand_id' => 1, 
        ]);

        Product::create([
            'name' => 'Dell UltraSharp U2720Q',
            'price' => 14000000,
            'stock' => 12,
            'description' => '27" 4K monitor for professional use.',
            'image' => '/assets/images/products/dell_ultrasharp.png',
            'sold' => 22,
            'detail' => '3840x2160 resolution, IPS display, excellent color accuracy.',
            'specification' => '27", 4K UHD, USB-C, HDR, 99% sRGB',
            'important_information' => 'Ideal for photo and video editing.',
            'original_price' => 15000000.00,
            'discount' => 7,
            'sale' => false,
            'category_id' => 3, 
            'brand_id' => 4,
        ]);

        Product::create([
            'name' => 'Dell OptiPlex 3090',
            'price' => 9000000,
            'stock' => 20,
            'description' => 'Compact desktop for business needs.',
            'image' => '/assets/images/products/dell_optiplex_3090.png',
            'sold' => 15,
            'detail' => 'Intel Core i5-10400, 8GB RAM, 256GB SSD.',
            'specification' => 'Intel Core i5-10400, Windows 10 Pro, USB-C support.',
            'important_information' => 'Optimized for office environments.',
            'original_price' => 9500000,
            'discount' => 5,
            'sale' => true,
            'category_id' => 2, 
            'brand_id' => 4, 
        ]);

        Product::create([
            'name' => 'Lenovo IdeaCentre 3',
            'price' => 7000000,
            'stock' => 30,
            'description' => 'Affordable desktop PC for everyday use.',
            'image' => '/assets/images/products/lenovo_ideacentre.png',
            'sold' => 25,
            'detail' => 'AMD Ryzen 3, 8GB RAM, 1TB HDD.',
            'specification' => 'AMD Ryzen 3 3250U, Radeon Graphics, Windows 10 Home.',
            'important_information' => 'Great for basic tasks and web browsing.',
            'original_price' => 7500000,
            'discount' => 7,
            'sale' => true,
            'category_id' => 2,
            'brand_id' => 5,
        ]);

        Product::create([
            'name' => 'Samsung Smart Monitor M7',
            'price' => 5000000,
            'stock' => 18,
            'description' => 'Smart monitor with 4K resolution.',
            'image' => '/assets/images/products/samsung_monitor_m7.png',
            'sold' => 40,
            'detail' => '32", UHD 4K, Tizen OS, HDR10.',
            'specification' => '32", 4K UHD, HDMI, USB-C, built-in apps.',
            'important_information' => 'Perfect for work and entertainment.',
            'original_price' => 5500000,
            'discount' => 10,
            'sale' => true,
            'category_id' => 3, 
            'brand_id' => 8, 
        ]);

        Product::create([
            'name' => 'MSI Optix MAG274QRF',
            'price' => 7500000,
            'stock' => 12,
            'description' => 'High-performance gaming monitor.',
            'image' => '/assets/images/products/msi_optix.png',
            'sold' => 22,
            'detail' => '27", QHD 165Hz, 1ms response time.',
            'specification' => '27", 2560x1440, G-Sync, IPS panel.',
            'important_information' => 'Designed for competitive gaming.',
            'original_price' => 8000000,
            'discount' => 6,
            'sale' => true,
            'category_id' => 3, 
            'brand_id' => 6, 
        ]);

        Product::create([
            'name' => 'Intel Core i7-12700K Processor',
            'price' => 5000000,
            'stock' => 25,
            'description' => 'Powerful processor for gaming and productivity.',
            'image' => '/assets/images/products/intel_corei7.png',
            'sold' => 30,
            'detail' => '12 cores, 20 threads, 3.6GHz base clock.',
            'specification' => '12 cores, PCIe 5.0, supports DDR5.',
            'important_information' => 'Best for high-performance PCs.',
            'original_price' => 5500000,
            'discount' => 10,
            'sale' => true,
            'category_id' => 4, 
            'brand_id' => 14,
        ]);

        Product::create([
            'name' => 'Corsair RM750x Power Supply',
            'price' => 2000000,
            'stock' => 40,
            'description' => 'High-quality PSU with 80+ Gold certification.',
            'image' => '/assets/images/products/corsair_rm750x.png',
            'sold' => 45,
            'detail' => '750W, fully modular, 80+ Gold.',
            'specification' => '750W, silent operation, Japanese capacitors.',
            'important_information' => 'Perfect for gaming builds.',
            'original_price' => 2200000,
            'discount' => 9,
            'sale' => false,
            'category_id' => 4, 
            'brand_id' => 10, 
        ]);

        Product::create([
            'name' => 'MSI GeForce RTX 3060 Gaming X',
            'price' => 6500000,
            'stock' => 20,
            'description' => 'Powerful GPU for gaming and creative workloads.',
            'image' => '/assets/images/products/msi_geforce.png',
            'sold' => 18,
            'detail' => '12GB GDDR6, Ray Tracing, DLSS technology.',
            'specification' => 'Boost clock: 1807 MHz, 192-bit memory interface.',
            'important_information' => 'Supports 4K gaming and advanced graphical features.',
            'original_price' => 7000000,
            'discount' => 7,
            'sale' => true,
            'category_id' => 4, 
            'brand_id' => 6,
        ]);

        Product::create([
            'name' => 'Gigabyte AORUS Z590 Elite',
            'price' => 4000000,
            'stock' => 30,
            'description' => 'High-performance motherboard for gaming and overclocking.',
            'image' => '/assets/images/products/gigabyte_aorus.png',
            'sold' => 25,
            'detail' => 'Supports 11th Gen Intel CPUs, PCIe 4.0, Dual M.2 slots.',
            'specification' => 'ATX form factor, LGA1200 socket, RGB Fusion 2.0.',
            'important_information' => 'Ideal for gaming builds and advanced configurations.',
            'original_price' => 4500000,
            'discount' => 11,
            'sale' => true,
            'category_id' => 4, 
            'brand_id' => 9, 
        ]);

        Product::create([
            'name' => 'Corsair Vengeance LPX 16GB DDR4',
            'price' => 1500000,
            'stock' => 100,
            'description' => 'High-performance RAM designed for gaming PCs.',
            'image' => '/assets/images/products/corsair_vengeance_lpx.png',
            'sold' => 75,
            'detail' => '16GB (2x8GB), 3200MHz, C16 latency.',
            'specification' => 'Low-profile design, optimized for overclocking.',
            'important_information' => 'Compatible with most motherboards.',
            'original_price' => 1700000,
            'discount' => 12,
            'sale' => true,
            'category_id' => 4, 
            'brand_id' => 10,
        ]);

        Product::create([
            'name' => 'Seagate FireCuda 520 1TB SSD',
            'price' => 2500000,
            'stock' => 40,
            'description' => 'High-performance SSD for gaming and content creation.',
            'image' => '/assets/images/products/seagate_firecuda.png',
            'sold' => 20,
            'detail' => '1TB capacity, PCIe Gen 4.0, up to 5000MB/s read speed.',
            'specification' => 'Form Factor: M.2 2280, Endurance: 1800 TBW.',
            'important_information' => 'Perfect for gamers and professionals needing speed.',
            'original_price' => 2800000,
            'discount' => 11,
            'sale' => true,
            'category_id' => 6, 
            'brand_id' => 15,
        ]);

        Product::create([
            'name' => 'Seagate 1TB One Touch',
            'price' => 1100000,
            'stock' => 50,
            'description' => 'Portable external HDD with a sleek design and reliable performance.',
            'image' => '/assets/images/products/seagate_one_touch_1tb.png',
            'sold' => 15,
            'detail' => '1TB capacity, USB 3.2 Gen 1, compact and durable design.',
            'specification' => 'Compatibility: Windows and macOS, Backup: Sync Plus software included.',
            'important_information' => 'Perfect for backing up photos, videos, and documents on the go.',
            'original_price' => 1250000,
            'discount' => 12,
            'sale' => true,
            'category_id' => 6, 
            'brand_id' => 15, 
        ]);

        Product::create([
            'name' => 'Kingston DataTraveler Kyson 128GB',
            'price' => 180000,
            'stock' => 100,
            'description' => 'Stylish and portable USB flash drive for quick data transfers.',
            'image' => '/assets/images/products/kingston_kyson_128gb.png',
            'sold' => 50,
            'detail' => '128GB capacity, USB 3.2 Gen 1, metal casing for durability.',
            'specification' => 'Compatibility: Windows, macOS, Linux.',
            'important_information' => 'Ideal for everyday storage needs.',
            'original_price' => 200000,
            'discount' => 10,
            'sale' => true,
            'category_id' => 6, 
            'brand_id' => 16,
        ]);

        Product::create([
            'name' => 'Kingston DataTraveler Kyson 256GB',
            'price' => 350000,
            'stock' => 80,
            'description' => 'High-capacity USB flash drive with ultra-fast data transfer speeds.',
            'image' => '/assets/images/products/kingston_kyson_256gb.png',
            'sold' => 30,
            'detail' => '256GB capacity, USB 3.2 Gen 1, metal casing for durability.',
            'specification' => 'Compatibility: Windows, macOS, Linux.',
            'important_information' => 'Perfect for storing large files securely.',
            'original_price' => 400000,
            'discount' => 12,
            'sale' => true,
            'category_id' => 6, 
            'brand_id' => 16,
        ]);

        Product::create([
            'name' => 'Kingston A400 240GB SATA SSD',
            'price' => 350000,
            'stock' => 100,
            'description' => 'Reliable SATA SSD for enhancing system performance.',
            'image' => '/assets/images/products/kingston_a400.png',
            'sold' => 60,
            'detail' => '240GB capacity, SATA III, durable design.',
            'specification' => 'Read Speed: Up to 500MB/s, Write Speed: Up to 450MB/s.',
            'important_information' => 'Affordable SSD upgrade for older systems.',
            'original_price' => 400000,
            'discount' => 12,
            'sale' => true,
            'category_id' => 6, 
            'brand_id' => 16,
        ]);

        Product::create([
            'name' => 'TP-Link Archer AX10 Wi-Fi 6 Router',
            'price' => 600000,
            'stock' => 70,
            'description' => 'Next-gen Wi-Fi 6 router for ultra-fast and stable internet speeds.',
            'image' => '/assets/images/products/tp-link_archer_ax10.png',
            'sold' => 40,
            'detail' => 'Wi-Fi 6, dual-band (2.4GHz & 5GHz), 4 Gigabit Ethernet ports.',
            'specification' => 'Speed: Up to 1500Mbps, Coverage: 1500 sq. ft.',
            'important_information' => 'Supports up to 128 devices for a large home or office.',
            'original_price' => 700000,
            'discount' => 14,
            'sale' => true,
            'category_id' => 7,
            'brand_id' => 17,
        ]);

        Product::create([
            'name' => 'TP-Link Deco X20 Mesh Wi-Fi System',
            'price' => 2300000,
            'stock' => 30,
            'description' => 'Mesh Wi-Fi system with seamless coverage for large homes and offices.',
            'image' => '/assets/images/products/tp-link_deco_x20.png',
            'sold' => 15,
            'detail' => 'Wi-Fi 6, coverage up to 5800 sq. ft., 3-pack system.',
            'specification' => 'Speed: Up to 1800Mbps, supports 100+ devices.',
            'important_information' => 'Ideal for large homes with multiple users and devices.',
            'original_price' => 2600000,
            'discount' => 12,
            'sale' => true,
            'category_id' => 7,
            'brand_id' => 17,
        ]);

        Product::create([
            'name' => 'D-Link DIR-825 AC1200 Wi-Fi Router',
            'price' => 450000,
            'stock' => 90,
            'description' => 'Budget-friendly router with reliable performance for daily use.',
            'image' => '/assets/images/products/dlink_dir_825.png',
            'sold' => 50,
            'detail' => 'AC1200, dual-band, 4 Ethernet ports, smart QoS.',
            'specification' => 'Speed: Up to 1200Mbps, Coverage: 1000 sq. ft.',
            'important_information' => 'Affordable router for homes with moderate internet use.',
            'original_price' => 500000,
            'discount' => 10,
            'sale' => true,
            'category_id' => 7,
            'brand_id' => 18,
        ]);

        Product::create([
            'name' => 'D-Link DIR-850L AC1200 Wi-Fi Router',
            'price' => 450000,
            'stock' => 150,
            'description' => 'High-speed Wi-Fi router with AC1200 support, ideal for streaming and gaming.',
            'image' => '/assets/images/products/dlink_dir850l.png',
            'sold' => 75,
            'detail' => 'Supports dual-band Wi-Fi, 4 Gigabit Ethernet ports, and easy setup via the D-Link app.',
            'specification' => 'Wi-Fi Standard: 802.11ac, Frequency: 2.4GHz/5GHz, Ports: 4x Gigabit Ethernet.',
            'important_information' => 'Ideal for home and small office use with a strong wireless range.',
            'original_price' => 500000,
            'discount' => 10,
            'sale' => true,
            'category_id' => 7,
            'brand_id' => 18,    
        ]);

        Product::create([
            'name' => 'D-Link DGS-108 8-Port Gigabit Switch',
            'price' => 650000,
            'stock' => 100,
            'description' => '8-Port Gigabit Ethernet Switch for high-speed wired connections and seamless network expansion.',
            'image' => '/assets/images/products/dlink_dgs108.png',
            'sold' => 45,
            'detail' => 'Compact 8-port design with full-duplex data transfer, ideal for home and office networking.',
            'specification' => 'Ports: 8 x Gigabit Ethernet, Mountable, Plug and Play, Energy Efficient.',
            'important_information' => 'Supports high-speed data transfer for a reliable wired network setup.',
            'original_price' => 700000,
            'discount' => 7,
            'sale' => true,
            'category_id' => 7,
            'brand_id' => 18,   
        ]);

        Product::create([
            'name' => 'Logitech MK270 Wireless Keyboard and Mouse Combo',
            'price' => 450000,
            'stock' => 80,
            'description' => 'Wireless keyboard and mouse combo for a comfortable and clutter-free workspace.',
            'image' => '/assets/images/products/logitech_mk270.png',
            'sold' => 60,
            'detail' => 'Includes a full-size keyboard and a wireless mouse with 2.4GHz connectivity for uninterrupted use.',
            'specification' => 'Connectivity: 2.4 GHz wireless, Battery Life: Up to 24 months (keyboard), 12 months (mouse).',
            'important_information' => 'Reliable wireless connection with plug-and-play USB receiver.',
            'original_price' => 500000,
            'discount' => 10,
            'sale' => true,
            'category_id' => 5,
            'brand_id' => 11,
        ]);

        Product::create([
            'name' => 'Rexus Xierra X17',
            'price' => 250000,
            'stock' => 20,
            'description' => 'High-precision RGB gaming mouse with customizable buttons and ergonomic design.',
            'image' => '/assets/images/products/rexus_m2.png',
            'sold' => 70,
            'detail' => 'Equipped with a 3200 DPI sensor, customizable RGB lighting, and 6 programmable buttons.',
            'specification' => 'DPI: 3200, Connectivity: Wired, RGB Lighting: Customizable.',
            'important_information' => 'Perfect for gamers who need precision and comfort during long sessions.',
            'original_price' => 300000,
            'discount' => 15,
            'sale' => true,
            'category_id' => 5,
            'brand_id' => 12, 
        ]);

        Product::create([
            'name' => 'Logitech G331 Wired Gaming Headset',
            'price' => 650000,
            'stock' => 60,
            'description' => 'High-quality wired gaming headset with 7.1 surround sound and adjustable noise-cancelling mic.',
            'image' => '/assets/images/products/logitech_g331.png',
            'sold' => 40,
            'detail' => 'Features 50mm drivers for immersive sound and an adjustable noise-canceling microphone.',
            'specification' => 'Connectivity: Wired (3.5mm), Sound: 7.1 Surround, Microphone: Adjustable Noise-Canceling.',
            'important_information' => 'Perfect for gaming, voice chat, and multimedia.',
            'original_price' => 700000,
            'discount' => 8,
            'sale' => true,
            'category_id' => 5,
            'brand_id' => 11,
        ]);
    }
}